baseurl = "http://www.example.com"
title = "jipdev"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "jip stavenuiter"
  info = "full stack developer"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  #avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = "Enter a text here."
  hideFooter = true
  hideCredits = true
  hideCopyright = true
  since = 2019

  enableTwemoji = true

  colorscheme = "dark"
  hidecolorschemetoggle = true


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Jipperism"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/jip-stavenuiter-061354119/"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:jipstavenuiter@gmail.com"

# Menu links
[[menu.main]]
  name = "projects"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "about me"
  weight = 2
  url = "about/"